version: '3.8'

services:
  app:
    image: openjdk:17-jdk
    container_name: gestao-trafego-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gestao_trafego
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: